#ifndef PLATFORM_ABSTRACTION_MEMORY_MANAGEMENT_VIRTUAL_H
#define PLATFORM_ABSTRACTION_MEMORY_MANAGEMENT_VIRTUAL_H

#ifdef X86_ARCHITECTURE
#include "x86/memory/virtual.h"
#else
#error "Could not match ARCHITECTURE"
#endif

#endif
