#ifndef PLATFORM_ABSTRACTION_MEMORY_MANAGEMENT_STATUS_H
#define PLATFORM_ABSTRACTION_MEMORY_MANAGEMENT_STATUS_H

#ifdef X86_ARCHITECTURE
#include "x86/memory/status.h"
#else
#error "Could not match ARCHITECTURE"
#endif

#endif
